using System.IO;
using InControl;
using UnityEngine.UI;

namespace GodhomeQoL.Modules.Tools;

public sealed partial class QuickMenu : Module
{
    private sealed partial class QuickMenuController : MonoBehaviour
    {
        private const int QuickCanvasSortOrder = 10000;
        private const int OverlayCanvasSortOrder = 10001;
        private const int CollectorCanvasSortOrder = 10002;
        private const int FastReloadCanvasSortOrder = 10003;
        private const int DreamshieldCanvasSortOrder = 10004;
        private const int ShowHpOnDeathCanvasSortOrder = 10005;
        private const int SpeedChangerCanvasSortOrder = 10006;
        private const int TeleportKitCanvasSortOrder = 10007;
        private const int BossChallengeCanvasSortOrder = 10008;
        private const int RandomPantheonsCanvasSortOrder = 10009;
        private const int QolCanvasSortOrder = 10010;
        private const int MenuAnimationCanvasSortOrder = 10011;
        private const int BossAnimationCanvasSortOrder = 10012;
        private const int ZoteHelperCanvasSortOrder = 10013;
        private const int QuickSettingsCanvasSortOrder = 10014;
        private const int AlwaysFuriousCanvasSortOrder = 10015;
        private const int GearSwitcherCanvasSortOrder = 10016;
        private const int GearSwitcherCharmCostCanvasSortOrder = 10017;
        private const int GearSwitcherPresetCanvasSortOrder = 10018;
        private const int MaskDamageCanvasSortOrder = 10019;
        private const int FreezeHitboxesCanvasSortOrder = 10020;
        private const int StatusCanvasSortOrder = 10050;
        private const float QuickMenuFadeSeconds = 0.4f;
        private const float QuickPanelBackplateAlpha = 0f;
        private const float QuickPanelWidth = 300f;
        private const float QuickPanelHeight = 520f;
        private const float QuickPanelDefaultLeft = 20f;
        private const float QuickPanelDefaultTop = -20f;
        private const float QuickPanelFreeWidth = 1920f;
        private const float QuickPanelFreeHeight = 1080f;
        private const float QuickSettingsPanelHeight = 1100f;
        private const float QuickSettingsRowStartY = 320f;
        private static readonly Color OverlayDimColor = new Color(0f, 0f, 0f, 0.55f);
        private static readonly Color OverlayPanelColor = new Color(0f, 0f, 0f, 0.75f);
        private const float QuickButtonWidth = 260f;
        private const float QuickButtonHeight = 36f;
        private const float QuickHandleWidth = 28f;
        private const float QuickHandleGap = 6f;
        private const float QuickRowWidth = QuickButtonWidth + QuickHandleWidth + QuickHandleGap;
        private const float DisabledContentAlpha = 0.45f;
        private const float QuickButtonLeft = 6f;
        private const float QuickButtonTop = -12f;
        private const float QuickButtonSpacing = 3f;
        private const float QuickCollectorIconSize = 32f;
        private const float QuickCollectorIconPadding = 6f;
        private const float QuickZoteIconSize = 32f;
        private const float PanelWidth = 960f;
        private const float PanelHeight = 1100f;
        private const float ZoteHelperPanelHeight = PanelHeight;
        private const float MenuAnimationPanelHeight = PanelHeight;
        private const float MenuAnimationRowStartY = 160f;
        private const float BossAnimationPanelHeight = PanelHeight;
        private const float BossAnimationRowStartY = 260f;
        private const float SpeedChangerPanelHeight = PanelHeight;
        private const float SpeedChangerRowStartY = 200f;
        private const float SpeedChangerRowSpacing = 60f;
        private const float BossChallengePanelHeight = PanelHeight;
        private const float BossChallengeRowStartY = 320f;
        private const float BossChallengeRowSpacing = 44f;
        private const float ZoteHelperRowSpacing = 44f;
        private const float QolRowSpacing = 44f;
        private const float GearSwitcherRowSpacing = 60f;
        private const float ToggleRowIconSize = 28f;
        private const float ToggleRowIconSpacing = 8f;
        private const float RowWidth = 820f;
        private const float RowHeight = 44f;
        private const float GearSwitcherBindingIconScale = 0.7f;
        private const float GearSwitcherHpMaskIconOffset = 50f;
        private const float GearSwitcherSoulVesselIconOffset = 60f;
        private const float GearSwitcherCharmCostRowHeight = 120f;
        private const float GearSwitcherCharmCostRowSpacing = 120f;
        private const float GearSwitcherCharmCostColumnStep = 130f;
        private const float GearSwitcherCharmCostIconY = 16f;
        private const float GearSwitcherCharmCostValueY = -24f;
        private const float GearSwitcherCharmCostValueWidth = 40f;
        private const int GearSwitcherCharmCostValueFontSize = 22;
        private const float GearSwitcherCharmCostButtonOffset = 22f;
        private const float GearSwitcherCharmCostIconHeight = 64f;
        private const float GearSwitcherCharmSwapBadgeWidth = 34f;
        private const float GearSwitcherCharmSwapBadgeHeight = 16f;
        private const int GearSwitcherCharmSwapBadgeFontSize = 12;
        private const float GearSwitcherCharmPromptRowHeight = 88f;
        private const float GearSwitcherPresetEditIconSize = 26f;
        private const float GearSwitcherPresetEditIconRightPadding = 54f;
        private const float GearSwitcherPresetDeleteIconSize = 26f;
        private const float GearSwitcherPresetDeleteIconRightPadding = 20f;
        private const float GearSwitcherNaillessIconOffset = 50f;
        private const float GearSwitcherTitleY = 430f;
        private const float GearSwitcherHintY = 380f;
        private const float GearSwitcherHintHeight = 28f;
        private const float GearSwitcherContentRowStartY = 300f;
        private const float GearSwitcherContentTopPadding = 10f;
        private const float RowStartY = 120f;
        private const float GearSwitcherRowStartY = 120f;
        private const float GearSwitcherTopPadding = 60f;
        private const float RowSpacing = 60f;
        private const float ButtonRowHeight = 48f;
        private const float FixedBackOffset = 110f;
        private const float FixedResetOffset = 170f;
        private const float ScrollTopPadding = 20f;
        private const float ScrollBottomPadding = 10f;
        private const float ScrollbarWidth = 8f;
        private const float ScrollbarRightPadding = 10f;
        private const float CollectorPanelWidth = PanelWidth;
        private const float CollectorPanelHeight = PanelHeight;
        private const float CollectorRowWidth = 920f;
        private const float CollectorRowHeight = 40f;
        private const float CollectorRowStartY = 320f;
        private const float CollectorRowSpacing = 44f;
        private const float CollectorLabelWidth = 700f;
        private const int CollectorTitleFontSize = 46;
        private const int CollectorLabelFontSize = 26;
        private const int CollectorValueFontSize = 26;
        private const float CollectorControlButtonWidth = 32f;
        private const float CollectorControlButtonHeight = 28f;
        private const float CollectorControlValueWidth = 80f;
        private const float CollectorControlGap = 8f;
        private const float CollectorControlPlusRight = -16f;
        private const float CollectorControlValueRight = CollectorControlPlusRight - CollectorControlButtonWidth - CollectorControlGap;
        private const float CollectorControlMinusRight = CollectorControlValueRight - CollectorControlValueWidth - CollectorControlGap;
        private const float InputControlButtonWidth = 32f;
        private const float InputControlButtonHeight = 28f;
        private const float InputControlValueWidth = 80f;
        private const float InputControlGap = 8f;
        private const float InputControlPlusRight = -16f;
        private const float InputControlValueRight = InputControlPlusRight - InputControlButtonWidth - InputControlGap;
        private const float InputControlMinusRight = InputControlValueRight - InputControlValueWidth - InputControlGap;
        private const float GearSwitcherSpellIconOffset = 70f;
        private static readonly Color GearSwitcherSpellInactiveColor = new Color(1f, 1f, 1f, 0.35f);
        private static readonly Color GearSwitcherSpellActiveColor = new Color(1f, 1f, 1f, 1f);
        private static readonly Color GearSwitcherSpellGlowColor = new Color(1f, 1f, 1f, 0.8f);
        private static readonly Color GearSwitcherBindingGlowColor = new Color(1f, 0.88f, 0.35f, 0.95f);
        private static readonly Color GearSwitcherCharmCostGlowColor = new Color(1f, 0.25f, 0.25f, 1f);
        private static readonly Color GearSwitcherCharmCostChangedValueColor = new Color(1f, 0.65f, 0.2f, 1f);
        private static readonly Color GearSwitcherPresetEditedColor = new Color(1f, 0.25f, 0.25f, 1f);
        private static readonly GearPreset DefaultGearPreset = new();
        private static readonly Color GearSwitcherBindingActiveColor = new Color(1f, 0.95f, 0.7f, 1f);
        private static readonly Color QuickMenuBaseColor = new Color(0f, 0f, 0f, 0.85f);
        private static readonly Color QuickMenuZoteEnabledColor = new Color(0.1f, 0.45f, 0.1f, 0.85f);
        private static readonly Color QuickMenuZoteDisabledColor = new Color(0.45f, 0.1f, 0.1f, 0.85f);
        private static readonly string[] SpeedChangerDisplayOptions = new[] { "#.##", "%", "Off" };
        private static readonly string[] BossChallengeGpzOptions = new[]
        {
            "Settings/gpzEnterType/Off".Localize(),
            "Settings/gpzEnterType/Long".Localize(),
            "Settings/gpzEnterType/Short".Localize()
        };
        private static Sprite? quickHandleSprite;
        private static Sprite? toggleShadeSprite;
        private static Sprite? collectorIconLeftSprite;
        private static Sprite? collectorIconRightSprite;
        private static Sprite? zoteIconLeftSprite;
        private static Sprite? zoteIconRightSprite;
        private static Sprite? vengefulSpiritSprite;
        private static Sprite? shadeSoulSprite;
        private static Sprite? desolateDiveSprite;
        private static Sprite? descendingDarkSprite;
        private static Sprite? howlingWraithsSprite;
        private static Sprite? abyssShriekSprite;
        private static Sprite? cycloneSlashSprite;
        private static Sprite? dashSlashSprite;
        private static Sprite? greatSlashSprite;
        private static Sprite? mothwingCloakSprite;
        private static Sprite? shadeCloakSprite;
        private static Sprite? mantisClawSprite;
        private static Sprite? monarchWingsSprite;
        private static Sprite? crystalHeartSprite;
        private static Sprite? ismasTearSprite;
        private static Sprite? dreamNailSprite;
        private static Sprite? awokenDreamNailSprite;
        private static Sprite? dreamgateSprite;
        private static Sprite? nailBindingSprite;
        private static Sprite? shellBindingSprite;
        private static Sprite? charmsBindingSprite;
        private static Sprite? soulBindingSprite;
        private static Sprite? nailBindingSelectedSprite;
        private static Sprite? shellBindingSelectedSprite;
        private static Sprite? charmsBindingSelectedSprite;
        private static Sprite? soulBindingSelectedSprite;
        private static Sprite? hpMaskSprite;
        private static Sprite? soulVesselSprite;
        private static Sprite? naillessSprite;
        private static Sprite? overcharmedSprite;
        private static Sprite? charmsPromptSprite;
        private static Sprite? gearSwitcherPresetEditSprite;
        private static Sprite? gearSwitcherPresetDeleteSprite;
        private static Sprite? voidHeartSprite;
        private static Sprite? kingsoulSprite;
        private static Sprite? grimmchildSprite;
        private static Sprite? carefreeMelodySprite;

        private GameObject? quickRoot;
        private RectTransform? quickPanelRect;
        private RectTransform? quickPanelBackplateRect;
        private RectTransform? quickPanelContentRect;
        private Image? quickPanelImage;
        private CanvasGroup? quickPanelGroup;
        private Coroutine? quickMenuFadeCoroutine;
        private float quickMenuFadeAlpha = 1f;
        private float quickMenuOpacityAlpha = 1f;
        private GameObject? quickSettingsRoot;
        private GameObject? overlayRoot;
        private GameObject? collectorRoot;
        private GameObject? fastReloadRoot;
        private GameObject? dreamshieldRoot;
        private GameObject? showHpOnDeathRoot;
        private GameObject? speedChangerRoot;
        private GameObject? teleportKitRoot;
        private GameObject? bossChallengeRoot;
        private GameObject? randomPantheonsRoot;
        private GameObject? maskDamageRoot;
        private GameObject? freezeHitboxesRoot;
        private RectTransform? bossChallengeContent;
        private RectTransform? randomPantheonsContent;
        private RectTransform? fastSuperDashContent;
        private RectTransform? collectorContent;
        private RectTransform? fastReloadContent;
        private RectTransform? dreamshieldContent;
        private RectTransform? showHpOnDeathContent;
        private RectTransform? maskDamageContent;
        private RectTransform? freezeHitboxesContent;
        private RectTransform? speedChangerContent;
        private RectTransform? teleportKitContent;
        private RectTransform? gearSwitcherContent;
        private RectTransform? gearSwitcherTitleRect;
        private RectTransform? gearSwitcherHintRect;
        private RectTransform? zoteHelperContent;
        private GameObject? alwaysFuriousRoot;
        private GameObject? gearSwitcherRoot;
        private GameObject? gearSwitcherCharmCostRoot;
        private GameObject? gearSwitcherPresetRoot;
        private GameObject? qolRoot;
        private RectTransform? qolContent;
        private ScrollRect? qolScrollRect;
        private GameObject? menuAnimationRoot;
        private RectTransform? menuAnimationContent;
        private GameObject? bossAnimationRoot;
        private RectTransform? bossAnimationContent;
        private GameObject? zoteHelperRoot;
        private GameObject? statusRoot;
        private bool quickVisible;
        private bool quickSettingsVisible;
        private bool overlayVisible;
        private bool collectorVisible;
        private bool fastReloadVisible;
        private bool dreamshieldVisible;
        private bool showHpOnDeathVisible;
        private bool speedChangerVisible;
        private bool teleportKitVisible;
        private bool bossChallengeVisible;
        private bool randomPantheonsVisible;
        private bool alwaysFuriousVisible;
        private bool maskDamageVisible;
        private bool freezeHitboxesVisible;
        private bool gearSwitcherVisible;
        private bool gearSwitcherCharmCostVisible;
        private bool gearSwitcherPresetVisible;
        private bool qolVisible;
        private bool menuAnimationVisible;
        private bool bossAnimationVisible;
        private bool zoteHelperVisible;
        private readonly List<QuickMenuEntry> quickEntries = new();
        private readonly Dictionary<string, Text> quickSettingsToggleValues = new();
        private readonly Dictionary<string, Text> quickSettingsHotkeyValues = new();
        private Text? quickMenuOpacityValue;
        private Slider? quickMenuOpacitySlider;
        private QuickMenuEntry? draggingQuickEntry;
        private Vector2 draggingQuickOffset;
        private int draggingQuickIndex = -1;
        private bool quickRenameMode;
        private QuickMenuEntry? renameEntry;
        private InputField? renameField;
        private string? renameOriginalLabel;
        private bool renameCancelled;
        private bool quickRenameSubmitPending;
        private bool uiActive;
        private bool returnToQuickOnClose;
        private bool returnToQolOnClose;
        private bool prevCursorVisible;
        private CursorLockMode prevCursorLock;
        private bool prevAllowMouseInput;
        private bool prevForceModuleActive;
        private bool cursorHookActive;
        private RowHighlight? manualHighlight;
        private PointerEventData? hoverEventData;
        private EventSystem? hoverEventSystem;
        private readonly List<RaycastResult> hoverResults = new();
        private Text? statusText;
        private float statusHideTime;
        private bool waitingForReloadRebind;
        private bool waitingForShowHpRebind;
        private bool waitingForSpeedToggleRebind;
        private bool waitingForSpeedInputRebind;
        private bool waitingForTeleportKitMenuRebind;
        private bool waitingForTeleportKitSaveRebind;
        private bool waitingForTeleportKitTeleportRebind;
        private bool waitingForMaskDamageUiRebind;
        private bool waitingForFreezeHitboxesRebind;
        private bool waitingForFastDreamWarpRebind;
        private bool waitingForQuickMenuHotkeyRebind;
        private bool waitingForOverlayHotkeyRebind;
        private string maskDamageUiPrevKey = string.Empty;
        private string freezeHitboxesPrevKey = string.Empty;
        private KeyCode reloadPrevKey;
        private KeyCode quickMenuPrevKey;
        private string overlayHotkeyRebindId = string.Empty;
        private KeyCode overlayHotkeyPrevKey = KeyCode.None;
        private InputControlType overlayHotkeyPrevButton;
        private KeyCode overlayHotkeySuppressKey = KeyCode.None;
        private InputControlType overlayHotkeySuppressButton;
        private bool overlayHotkeySuppressActive;
        private int overlayHotkeySuppressFrames;
        private string showHpPrevBindingRaw = string.Empty;
        private string speedTogglePrevKey = string.Empty;
        private string speedInputPrevKey = string.Empty;
        private string fastDreamWarpPrevKeyRaw = string.Empty;
        private InputControlType fastDreamWarpPrevButton;

        private Text? moduleToggleValue;
        private Image? moduleToggleIcon;
        private Text? instantToggleValue;
        private Text? everywhereToggleValue;
        private Text? speedValueText;
        private Slider? speedSlider;
        private Module? fastSuperDashModule;
        private Text? collectorModuleToggleValue;
        private Image? collectorModuleToggleIcon;
        private Text? collectorHoGOnlyValue;
        private Text? collectorPhaseValue;
        private Text? collectorImmortalValue;
        private Text? ignoreInitialJarLimitValue;
        private Text? useCustomPhase2ThresholdValue;
        private InputField? customPhase2ThresholdField;
        private Text? useMaxHpValue;
        private InputField? collectorMaxHpField;
        private InputField? buzzerHpField;
        private Text? spawnBuzzerValue;
        private InputField? rollerHpField;
        private Text? spawnRollerValue;
        private InputField? spitterHpField;
        private Text? spawnSpitterValue;
        private Text? disableSummonLimitValue;
        private InputField? customSummonLimitField;
        private Module? collectorPhasesModule;
        private Text? fastReloadToggleValue;
        private Image? fastReloadToggleIcon;
        private Text? reloadKeyValue;
        private Module? fastReloadModule;
        private Module? maskDamageModule;
        private Module? freezeHitboxesModule;
        private Text? dreamshieldToggleValue;
        private Image? dreamshieldToggleIcon;
        private Text? dreamshieldDelayValue;
        private Text? dreamshieldSpeedValue;
        private Slider? dreamshieldDelaySlider;
        private Slider? dreamshieldSpeedSlider;
        private Text? showHpGlobalValue;
        private Image? showHpGlobalIcon;
        private Text? showHpShowPbValue;
        private Text? showHpAutoHideValue;
        private Text? showHpHudToggleKeyValue;
        private Text? fastDreamWarpKeyValue;
        private Text? showHpFadeValue;
        private Slider? showHpFadeSlider;
        private Text? maskDamageToggleValue;
        private Image? maskDamageToggleIcon;
        private InputField? maskDamageMultiplierField;
        private Text? maskDamageToggleUiKeyValue;
        private Text? freezeHitboxesToggleValue;
        private Image? freezeHitboxesToggleIcon;
        private Text? freezeHitboxesModeValue;
        private Text? freezeHitboxesUnfreezeKeyValue;
        private Text? speedChangerGlobalValue;
        private Image? speedChangerGlobalIcon;
        private Text? speedChangerRestrictValue;
        private Text? speedChangerUnlimitedValue;
        private Text? speedChangerDisplayValue;
        private Text? speedChangerToggleKeyValue;
        private Text? speedChangerInputKeyValue;
        private Module? speedChangerModule;
        private Text? teleportKitToggleValue;
        private Image? teleportKitToggleIcon;
        private Text? teleportKitMenuKeyValue;
        private Text? teleportKitSaveKeyValue;
        private Text? teleportKitTeleportKeyValue;
        private Module? teleportKitModule;
        private Text? bossInfiniteChallengeValue;
        private Text? bossRestartOnSuccessValue;
        private Text? bossRestartAndMusicValue;
        private Text? bossForceArriveValue;
        private Text? alwaysFuriousToggleValue;
        private Image? alwaysFuriousToggleIcon;
        private Text? gearSwitcherEnableValue;
        private Image? gearSwitcherEnableIcon;
        private Text? gearSwitcherSelectedPresetValue;
        private InputField? gearSwitcherNailDamageField;
        private InputField? gearSwitcherCharmSlotsField;
        private InputField? gearSwitcherMainSoulGainField;
        private InputField? gearSwitcherReserveSoulGainField;
        private Image? gearSwitcherFireballIcon;
        private Outline? gearSwitcherFireballGlow;
        private Image? gearSwitcherQuakeIcon;
        private Outline? gearSwitcherQuakeGlow;
        private Image? gearSwitcherScreamIcon;
        private Outline? gearSwitcherScreamGlow;
        private Image? gearSwitcherCloakIcon;
        private Outline? gearSwitcherCloakGlow;
        private Image? gearSwitcherMantisClawIcon;
        private Outline? gearSwitcherMantisClawGlow;
        private Image? gearSwitcherMonarchWingsIcon;
        private Outline? gearSwitcherMonarchWingsGlow;
        private Image? gearSwitcherCrystalHeartIcon;
        private Outline? gearSwitcherCrystalHeartGlow;
        private Image? gearSwitcherIsmasTearIcon;
        private Outline? gearSwitcherIsmasTearGlow;
        private Image? gearSwitcherDreamNailIcon;
        private Outline? gearSwitcherDreamNailGlow;
        private Image? gearSwitcherDreamgateIcon;
        private Outline? gearSwitcherDreamgateGlow;
        private Image? gearSwitcherBindingNailIcon;
        private Outline? gearSwitcherBindingNailGlow;
        private Image? gearSwitcherBindingShellIcon;
        private Outline? gearSwitcherBindingShellGlow;
        private Image? gearSwitcherBindingCharmsIcon;
        private Outline? gearSwitcherBindingCharmsGlow;
        private Image? gearSwitcherBindingSoulIcon;
        private Outline? gearSwitcherBindingSoulGlow;
        private Image? gearSwitcherCharmPromptIcon;
        private Image? gearSwitcherCarefreeIcon;
        private Image? gearSwitcherVoidHeartIcon;
        private Text? gearSwitcherWaywardCostValue;
        private Text? gearSwitcherGatheringCostValue;
        private Text? gearSwitcherStalwartShellCostValue;
        private Text? gearSwitcherSoulCatcherCostValue;
        private Text? gearSwitcherShamanStoneCostValue;
        private Text? gearSwitcherSoulEaterCostValue;
        private Text? gearSwitcherDashmasterCostValue;
        private Text? gearSwitcherSprintmasterCostValue;
        private Text? gearSwitcherGrubsongCostValue;
        private Text? gearSwitcherGrubberflysElegyCostValue;
        private Text? gearSwitcherUnbreakableHeartCostValue;
        private Text? gearSwitcherUnbreakableGreedCostValue;
        private Text? gearSwitcherUnbreakableStrengthCostValue;
        private Text? gearSwitcherSpellTwisterCostValue;
        private Text? gearSwitcherSteadyBodyCostValue;
        private Text? gearSwitcherHeavyBlowCostValue;
        private Text? gearSwitcherQuickSlashCostValue;
        private Text? gearSwitcherLongnailCostValue;
        private Text? gearSwitcherMarkOfPrideCostValue;
        private Text? gearSwitcherFuryOfTheFallenCostValue;
        private Text? gearSwitcherThornsOfAgonyCostValue;
        private Text? gearSwitcherBaldurShellCostValue;
        private Text? gearSwitcherFlukenestCostValue;
        private Text? gearSwitcherDefendersCrestCostValue;
        private Text? gearSwitcherGlowingWombCostValue;
        private Text? gearSwitcherQuickFocusCostValue;
        private Text? gearSwitcherDeepFocusCostValue;
        private Text? gearSwitcherLifebloodHeartCostValue;
        private Text? gearSwitcherLifebloodCoreCostValue;
        private Text? gearSwitcherJonisBlessingCostValue;
        private Text? gearSwitcherHivebloodCostValue;
        private Text? gearSwitcherSporeShroomCostValue;
        private Text? gearSwitcherSharpShadowCostValue;
        private Text? gearSwitcherShapeOfUnnCostValue;
        private Text? gearSwitcherNailmastersGloryCostValue;
        private Text? gearSwitcherWeaversongCostValue;
        private Text? gearSwitcherDreamWielderCostValue;
        private Text? gearSwitcherDreamshieldCostValue;
        private Text? gearSwitcherCarefreeMelodyCostValue;
        private Text? gearSwitcherVoidHeartCostValue;
        private readonly List<Image> gearSwitcherHpMaskIcons = new();
        private readonly List<Outline> gearSwitcherHpMaskGlows = new();
        private readonly List<Image> gearSwitcherSoulVesselIcons = new();
        private readonly List<Outline> gearSwitcherSoulVesselGlows = new();
        private Image? gearSwitcherNaillessIcon;
        private Outline? gearSwitcherNaillessGlow;
        private Image? gearSwitcherOvercharmedIcon;
        private Outline? gearSwitcherOvercharmedGlow;
        private Image? gearSwitcherCycloneIcon;
        private Outline? gearSwitcherCycloneGlow;
        private Image? gearSwitcherDashSlashIcon;
        private Outline? gearSwitcherDashSlashGlow;
        private Image? gearSwitcherGreatSlashIcon;
        private Outline? gearSwitcherGreatSlashGlow;
        private readonly List<RectTransform> gearSwitcherCloakRowIconRects = new();
        private readonly List<RectTransform> gearSwitcherBindingsRowIconRects = new();
        private readonly List<RectTransform> gearSwitcherHpMaskIconRects = new();
        private readonly List<RectTransform> gearSwitcherSoulVesselIconRects = new();
        private readonly Dictionary<string, Outline> gearSwitcherCharmCostGlows = new();
        private readonly List<CharmCostHighlightEntry> gearSwitcherCharmCostHighlightEntries = new();
        private readonly List<GearSwitcherPresetEntry> gearSwitcherPresetEntries = new();
        private string gearSwitcherSelectedPreset = string.Empty;
        private InputField? gearSwitcherPresetRenameField;
        private Text? gearSwitcherPresetRenameLabel;
        private string? gearSwitcherPresetRenameOriginalLabel;
        private string? gearSwitcherPresetRenameTargetName;
        private bool gearSwitcherPresetRenameCancelled;
        private bool gearSwitcherPresetRenameSubmitPending;
        private GameObject? gearSwitcherPresetDeleteRoot;
        private Text? gearSwitcherPresetDeleteLabel;
        private string? gearSwitcherPresetDeleteTargetName;
        private bool gearSwitcherPresetDeleteVisible;
        private GameObject? gearSwitcherResetConfirmRoot;
        private bool gearSwitcherResetConfirmVisible;
        private GameObject? quickSettingsResetConfirmRoot;
        private bool quickSettingsResetConfirmVisible;
        private Text? bossInfiniteGrimmValue;
        private Text? bossInfiniteRadianceValue;
        private Text? bossP5HealthValue;
        private Text? bossSegmentedP5Value;
        private Text? bossHalveAscendedValue;
        private Text? bossHalveAttunedValue;
        private Text? bossAddLifebloodValue;
        private InputField? bossLifebloodAmountField;
        private Text? bossAddSoulValue;
        private InputField? bossSoulAmountField;
        private Text? bossGpzValue;
        private Text? bossChallengeEnableValue;
        private Image? bossChallengeEnableIcon;
        private Text? randomPantheonsToggleValue;
        private Image? randomPantheonsToggleIcon;
        private Text? randomPantheonsP1Value;
        private Text? randomPantheonsP2Value;
        private Text? randomPantheonsP3Value;
        private Text? randomPantheonsP4Value;
        private Text? randomPantheonsP5Value;
        private bool bossChallengeMasterEnabled = true;
        private bool bossChallengeMasterHasSnapshot;
        private bool bossChallengeSavedInfiniteChallenge;
        private bool bossChallengeSavedRestartOnSuccess;
        private bool bossChallengeSavedRestartAndMusic;
        private int bossChallengeSavedCarefreeMelodyMode;
        private bool bossChallengeSavedInfiniteGrimm;
        private bool bossChallengeSavedInfiniteRadiance;
        private bool bossChallengeSavedP5Health;
        private bool bossChallengeSavedSegmentedP5;
        private bool bossChallengeSavedHalveAscended;
        private bool bossChallengeSavedHalveAttuned;
        private bool bossChallengeSavedAddLifeblood;
        private bool bossChallengeSavedAddSoul;
        private bool bossChallengeSavedForceArrive;
        private Module? infiniteChallengeModule;
        private Module? infiniteGrimmModule;
        private Module? infiniteRadianceModule;
        private Module? randomPantheonsModule;
        private Module? alwaysFuriousModule;
        private Module? p5HealthModule;
        private Module? segmentedP5Module;
        private Module? halveAscendedModule;
        private Module? halveAttunedModule;
        private Module? addLifebloodModule;
        private Module? addSoulModule;
        private Module? forceGreyPrinceModule;
        private Module? forceArriveAnimationModule;
        private Text? qolCarefreeMelodyValue;
        private Text? qolCollectorRoarValue;
        private Text? qolUnlockAllModesValue;
        private Text? qolUnlockPantheonsValue;
        private Text? qolUnlockRadianceValue;
        private Text? qolUnlockRadiantValue;
        private Text? qolInvincibleIndicatorValue;
        private Text? qolScreenShakeValue;
        private Text? qolEnableValue;
        private Image? qolEnableIcon;
        private bool qolMasterEnabled = true;
        private bool qolMasterHasSnapshot;
        private bool qolSavedFastDreamWarp;
        private bool qolSavedShortDeath;
        private bool qolSavedHallOfGods;
        private bool qolSavedUnlockAllModes;
        private bool qolSavedUnlockPantheons;
        private bool qolSavedUnlockRadiance;
        private bool qolSavedUnlockRadiant;
        private bool qolSavedInvincibleIndicator;
        private bool qolSavedScreenShake;
        private Text? menuAnimDoorDefaultValue;
        private Text? menuAnimMemorizeBindingsValue;
        private Text? menuAnimFasterLoadsValue;
        private Text? menuAnimFastMenusValue;
        private Text? menuAnimFastTextValue;
        private Text? menuAnimAutoSkipValue;
        private Text? menuAnimAllowSkippingValue;
        private Text? menuAnimSkipWithoutPromptValue;
        private Text? menuAnimEnableValue;
        private Image? menuAnimEnableIcon;
        private bool menuAnimMasterEnabled = true;
        private bool menuAnimMasterHasSnapshot;
        private bool menuAnimSavedDoorDefaultBegin;
        private bool menuAnimSavedMemorizeBindings;
        private bool menuAnimSavedFasterLoads;
        private bool menuAnimSavedFastMenus;
        private bool menuAnimSavedFastText;
        private bool menuAnimSavedAutoSkip;
        private bool menuAnimSavedAllowSkipping;
        private bool menuAnimSavedSkipWithoutPrompt;
        private Text? bossAnimFastDreamWarpValue;
        private Text? bossAnimShortDeathValue;
        private Text? bossAnimHallOfGodsValue;
        private Text? bossAnimAbsoluteRadianceValue;
        private Text? bossAnimPureVesselValue;
        private Text? bossAnimGrimmNightmareValue;
        private Text? bossAnimGreyPrinceValue;
        private Text? bossAnimCollectorValue;
        private Text? bossAnimSoulMasterValue;
        private Text? bossAnimEnableValue;
        private Image? bossAnimEnableIcon;
        private bool bossAnimMasterEnabled = true;
        private bool bossAnimMasterHasSnapshot;
        private bool bossAnimSavedAbsoluteRadiance;
        private bool bossAnimSavedPureVesselRoar;
        private bool bossAnimSavedGrimmNightmare;
        private bool bossAnimSavedGreyPrinceZote;
        private bool bossAnimSavedCollector;
        private bool bossAnimSavedSoulMaster;
        private bool randomPantheonsMasterEnabled = true;
        private bool randomPantheonsMasterHasSnapshot;
        private bool randomPantheonsSavedP1;
        private bool randomPantheonsSavedP2;
        private bool randomPantheonsSavedP3;
        private bool randomPantheonsSavedP4;
        private bool randomPantheonsSavedP5;
        private Text? zoteHelperToggleValue;
        private Image? zoteHelperToggleIcon;
        private Text? zoteHoGOnlyValue;
        private Text? zoteImmortalValue;
        private Text? zoteSpawnFlyingValue;
        private Text? zoteSpawnHoppingValue;
        private InputField? zoteBossHpField;
        private InputField? zoteSummonFlyingHpField;
        private InputField? zoteSummonHoppingHpField;
        private InputField? zoteSummonLimitField;
        private Module? carefreeMelodyModule;
        private Module? collectorRoarModule;
        private Module? unlockAllModesModule;
        private Module? unlockPantheonsModule;
        private Module? unlockRadianceModule;
        private Module? unlockRadiantModule;
        private Module? doorDefaultBeginModule;
        private Module? memorizeBindingsModule;
        private Module? fasterLoadsModule;
        private Module? fastMenusModule;
        private Module? fastTextModule;
        private Module? fastDreamWarpModule;
        private Module? shortDeathAnimationModule;
        private Module? invincibleIndicatorModule;
        private Module? screenShakeModule;
        private Module? zoteHelperModule;

    }
}
