namespace GodhomeQoL.Modules.Tools;

internal static class BossNames
{
    internal static readonly Dictionary<string, string> Map = new()
    {
        { "Giant Fly", "Gruz Mother" },
        { "Giant Buzzer Col", "Vengerfly King" },
        { "Giant Buzzer Col (1)", "Vengerfly King" },
        { "Mawlek Body", "Brooding Mawlek" },
        { "False Knight New", "False Knight" },
        { "False Knight Dream", "Failed Champion" },
        { "Hornet Boss 1", "Hornet Protector" },
        { "Hornet Boss 2", "Hornet Sentinel" },
        { "Mega Moss Charger", "Massive Moss Charger" },
        { "Fluke Mother", "Flukemarm" },
        { "Mantis Lord", "Mantis Lord Phase 1" },
        { "Mantis Lord S1", "Mantis Lord Phase 2" },
        { "Mantis Lord S2", "Mantis Lord Phase 2" },
        { "Mantis Lord S3", "Sisters Of Battle" },
        { "Mega Fat Bee", "Oblobbles" },
        { "Mega Fat Bee (1)", "Oblobbles" },
        { "Hive Knight", "Hive Knight" },
        { "Infected Knight", "Broken Vessel" },
        { "Lost Kin", "Lost Kin" },
        { "Mimic Spider", "Nosk" },
        { "Hornet Nosk", "Winged Nosk" },
        { "Jar Collector", "The Collector" },
        { "Lancer", "God Tamer" },
        { "Lobster", "Beast" },
        { "Mega Zombie Beam Miner (1)", "Crystal Guardian" },
        { "Zombie Beam Miner Rematch", "Enraged Guardian" },
        { "Mega Jellyfish GG", "Uumu" },
        { "Mantis Traitor Lord", "Traitor Lord" },
        { "Grey Prince", "Grey Prince Zote" },
        { "Mage Knight", "Soul Warrior" },
        { "Mage Lord", "Soul Master" },
        { "Mage Lord Phase2", "Soul Master" },
        { "Dream Mage Lord", "Soul Tyrant" },
        { "Dream Mage Lord Phase2", "Soul Tyrant" },
        { "Dung Defender", "Dung Defender" },
        { "White Defender", "White Defender" },
        { "Black Knight 1", "Watcher Knight" },
        { "Black Knight 2", "Watcher Knight" },
        { "Black Knight 3", "Watcher Knight" },
        { "Black Knight 4", "Watcher Knight" },
        { "Black Knight 5", "Watcher Knight" },
        { "Black Knight 6", "Watcher Knight" },
        { "Ghost Warrior No Eyes", "No Eyes" },
        { "Ghost Warrior Marmu", "Marmu" },
        { "Ghost Warrior Xero", "Xero" },
        { "Ghost Warrior Markoth", "Markoth" },
        { "Ghost Warrior Galien", "Galien" },
        { "Ghost Warrior Slug", "Gorb" },
        { "Ghost Warrior Hu", "Elder Hu" },
        { "Mato", "Mato" },
        { "Oro", "Oro" },
        { "Sheo Boss", "Paintmaster Sheo" },
        { "Sly Boss", "Nailsage Sly" },
        { "HK Prime", "Pure Vessel" },
        { "Grimm Boss", "Grimm" },
        { "Nightmare Grimm Boss", "Nightmare King" },
        { "Absolute Radiance", "Radiance" },
    };
}
